import { Button } from './ui/button'
import { Input } from './ui/input'
import { Select } from './ui/select'

type Props = Record<string, any>

export function FrameSection(props: Props) {
  const {
    uiLanguage, t, activeFrame, patchActiveFrame, PLOT_ALGORITHMS, automaticDisplayAreaActive,
    activeDataframe, numberValue, FieldComponent: Field,
  } = props

  return (
    <section className="grid gap-3 rounded-lg border border-zinc-200 p-4 dark:border-zinc-800 dark:bg-transparent sm:grid-cols-2">
      <h3 className="sm:col-span-2 text-sm font-semibold">Frame</h3>
      <Field language={uiLanguage} label="Export file name" jsonPath="frames[j].export_file_name"><Input value={activeFrame.exportFileName ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, exportFileName: e.target.value || undefined }))} /></Field>
      <Field language={uiLanguage} label="Algorithm" jsonPath="frames[j].algorithm"><Select value={activeFrame.algorithm} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, algorithm: e.target.value as any }))}>{PLOT_ALGORITHMS.map((a:string) => <option key={a} value={a}>{a}</option>)}</Select></Field>
      <Field language={uiLanguage} label="Automatic display area" jsonPath="automatic_Display_Area_margin"><div className="grid gap-2"><Button type="button" variant="outline" onClick={() => patchActiveFrame((c:any) => ({ ...c, automaticDisplayAreaMargin: c.automaticDisplayAreaMargin ? null : { left: 0, right: 0, top: 0, bottom: 0 } }))}>{automaticDisplayAreaActive ? 'active' : 'inactive'}</Button></div></Field>
      <div className="sm:col-span-2 grid gap-2 rounded-lg border border-zinc-300 p-3 dark:border-zinc-700"><h4 className="m-0 text-sm font-semibold">X-Axis</h4><div className="grid gap-2 sm:grid-cols-4"><Field language={uiLanguage} label="quantity" jsonPath="x_quantity"><Select value={activeFrame.xQuantity ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, xQuantity: e.target.value || undefined }))}><option value="" disabled>Select required axis</option>{activeDataframe.axes.map((axis:any) => <option key={axis.name} value={axis.name}>{axis.name}</option>)}</Select></Field><Field language={uiLanguage} label="relative quantity" jsonPath="x_rel_quantity"><Select value={activeFrame.xRelQuantity ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, xRelQuantity: e.target.value || undefined }))}><option value="">none</option>{activeDataframe.axes.map((axis:any) => <option key={`x-rel-${axis.name}`} value={axis.name}>{axis.name}</option>)}</Select></Field><Field language={uiLanguage} label={t('Logarithmic')} jsonPath="log_x_flag"><Button type="button" variant="outline" onClick={() => patchActiveFrame((c:any) => ({ ...c, logXFlag: !c.logXFlag }))}>{activeFrame.logXFlag === true ? t('scaleLog') : t('scaleLinear')}</Button></Field><div className="grid grid-cols-2 gap-2"><Field language={uiLanguage} label={automaticDisplayAreaActive ? 'left' : 'min'} jsonPath={automaticDisplayAreaActive ? 'automatic_Display_Area_margin.left' : 'x_lim[0]'}><Input type="number" value={automaticDisplayAreaActive ? (activeFrame.automaticDisplayAreaMargin?.left ?? 0) : (activeFrame.xLim?.[0] ?? '')} onChange={(e:any) => automaticDisplayAreaActive ? patchActiveFrame((c:any) => ({ ...c, automaticDisplayAreaMargin: { ...(c.automaticDisplayAreaMargin ?? { left: 0, right: 0, top: 0, bottom: 0 }), left: numberValue(e.target.valueAsNumber, c.automaticDisplayAreaMargin?.left ?? 0) } })) : patchActiveFrame((c:any) => ({ ...c, xLim: [numberValue(e.target.valueAsNumber, c.xLim?.[0] ?? 0), c.xLim?.[1] ?? 0] }))} /></Field><Field language={uiLanguage} label={automaticDisplayAreaActive ? 'right' : 'max'} jsonPath={automaticDisplayAreaActive ? 'automatic_Display_Area_margin.right' : 'x_lim[1]'}><Input type="number" value={automaticDisplayAreaActive ? (activeFrame.automaticDisplayAreaMargin?.right ?? 0) : (activeFrame.xLim?.[1] ?? '')} onChange={(e:any) => automaticDisplayAreaActive ? patchActiveFrame((c:any) => ({ ...c, automaticDisplayAreaMargin: { ...(c.automaticDisplayAreaMargin ?? { left: 0, right: 0, top: 0, bottom: 0 }), right: numberValue(e.target.valueAsNumber, c.automaticDisplayAreaMargin?.right ?? 0) } })) : patchActiveFrame((c:any) => ({ ...c, xLim: [c.xLim?.[0] ?? 0, numberValue(e.target.valueAsNumber, c.xLim?.[1] ?? 0)] }))} /></Field></div></div></div>
      <div className="sm:col-span-2 grid gap-2 rounded-lg border border-zinc-300 p-3 dark:border-zinc-700"><h4 className="m-0 text-sm font-semibold">Y-Axis</h4><div className="grid gap-2 sm:grid-cols-4"><Field language={uiLanguage} label="quantity" jsonPath="y_quantity"><Select value={activeFrame.yQuantity ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, yQuantity: e.target.value || undefined }))}><option value="" disabled>Select required axis</option>{activeDataframe.axes.map((axis:any) => <option key={axis.name} value={axis.name}>{axis.name}</option>)}</Select></Field><Field language={uiLanguage} label="relative quantity" jsonPath="y_rel_quantity"><Select value={activeFrame.yRelQuantity ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, yRelQuantity: e.target.value || undefined }))}><option value="">none</option>{activeDataframe.axes.map((axis:any) => <option key={`y-rel-${axis.name}`} value={axis.name}>{axis.name}</option>)}</Select></Field><Field language={uiLanguage} label={t('Logarithmic')} jsonPath="log_y_flag"><Button type="button" variant="outline" onClick={() => patchActiveFrame((c:any) => ({ ...c, logYFlag: !c.logYFlag }))}>{activeFrame.logYFlag === true ? t('scaleLog') : t('scaleLinear')}</Button></Field><div className="grid grid-cols-2 gap-2"><Field language={uiLanguage} label={automaticDisplayAreaActive ? 'bottom' : 'min'} jsonPath={automaticDisplayAreaActive ? 'automatic_Display_Area_margin.bottom' : 'y_lim[0]'}><Input type="number" value={automaticDisplayAreaActive ? (activeFrame.automaticDisplayAreaMargin?.bottom ?? 0) : (activeFrame.yLim?.[0] ?? '')} onChange={(e:any) => automaticDisplayAreaActive ? patchActiveFrame((c:any) => ({ ...c, automaticDisplayAreaMargin: { ...(c.automaticDisplayAreaMargin ?? { left: 0, right: 0, top: 0, bottom: 0 }), bottom: numberValue(e.target.valueAsNumber, c.automaticDisplayAreaMargin?.bottom ?? 0) } })) : patchActiveFrame((c:any) => ({ ...c, yLim: [numberValue(e.target.valueAsNumber, c.yLim?.[0] ?? 0), c.yLim?.[1] ?? 0] }))} /></Field><Field language={uiLanguage} label={automaticDisplayAreaActive ? 'top' : 'max'} jsonPath={automaticDisplayAreaActive ? 'automatic_Display_Area_margin.top' : 'y_lim[1]'}><Input type="number" value={automaticDisplayAreaActive ? (activeFrame.automaticDisplayAreaMargin?.top ?? 0) : (activeFrame.yLim?.[1] ?? '')} onChange={(e:any) => automaticDisplayAreaActive ? patchActiveFrame((c:any) => ({ ...c, automaticDisplayAreaMargin: { ...(c.automaticDisplayAreaMargin ?? { left: 0, right: 0, top: 0, bottom: 0 }), top: numberValue(e.target.valueAsNumber, c.automaticDisplayAreaMargin?.top ?? 0) } })) : patchActiveFrame((c:any) => ({ ...c, yLim: [c.yLim?.[0] ?? 0, numberValue(e.target.valueAsNumber, c.yLim?.[1] ?? 0)] }))} /></Field></div></div></div>
      <div className="grid gap-2"><label className="font-medium text-zinc-900 dark:text-zinc-100">Title</label>{activeDataframe.plotLanguages.map((lang:string) => (<div key={`title-${lang}`} className="grid grid-cols-[3rem_minmax(0,1fr)] items-center gap-2"><span className="text-xs uppercase text-zinc-600 dark:text-zinc-300">{lang}</span><Input value={activeFrame.title[lang] ?? ''} onChange={(e:any) => patchActiveFrame((c:any) => ({ ...c, title: { ...c.title, [lang]: e.target.value } }))} /></div>))}</div>
      <div className="grid gap-2"><label className="font-medium text-zinc-900 dark:text-zinc-100">Legend title</label>{activeDataframe.plotLanguages.map((lang:string) => (<div key={`legend-${lang}`} className="grid grid-cols-[3rem_minmax(0,1fr)] items-center gap-2"><span className="text-xs uppercase text-zinc-600 dark:text-zinc-300">{lang}</span><Input value={activeDataframe.legendTitle[lang] ?? ''} onChange={(e:any) => props.patchActiveDataframe((c:any) => ({ ...c, legendTitle: { ...c.legendTitle, [lang]: e.target.value } }))} /></div>))}</div>
    </section>
  )
}
